package evgenii.goncharov.econome.bank_accounts_impl.di.contracts

import evgenii.goncharov.econome.bank_accounts_api.di.AddPatternAccountApi

internal interface AddPatternAccountInternal : AddPatternAccountApi