package evgenii.goncharov.econome.finance_analysis_impl.di.contracts

import evgenii.goncharov.econome.finance_analysis_api.di.FinanceAnalyticsApi

internal interface FinanceAnalyticsInternal : FinanceAnalyticsApi