package evgenii.goncharov.econome.finance_analysis_impl.di.contracts

import evgenii.goncharov.econome.finance_analysis_api.di.FinanceAnalyticsAllSpendingApi

internal interface FinanceAnalyticsAllSpendingInternal : FinanceAnalyticsAllSpendingApi