package evgenii.goncharov.econome.product_cost_analysis_impl.di.contracts

import evgenii.goncharov.econome.product_cost_analysis_api.di.AddCostGoodsApi

internal interface AddCostGoodsInternal : AddCostGoodsApi